"""Master Dictionary mapping the number of the letter to a tuple (Author,place the letter was sent from,year of the letter)"""
letter_map = {
    1: ("Leibnitz", "Hannover", 1680),
    2: ("Leibnitz", "Zellerfeld", 1684),
    3: ("Leibnitz", "Hannover", 1684),
    4: ("Sophie", "Hannover", 1688),
    5: ("Leibnitz", "München", 1688),
    6: ("Sophie", "Herrenhausen", 1688),
    7: ("Leibnitz", "Wien", 1688),
    8: ("Leibnitz", "Wien", 1688),
    9: ("Sophie", "Herrenhausen", 1688),
    10: ("Leibnitz", "Wien", 1688),
    11: ("Sophie", "Berlin", 1688),
    12: ("Leibnitz", "Wien", 1688),
    13: ("Sophie", "Herrenhausen", 1688),
    14: ("Leibnitz", "Wien", 1688),
    15: ("Leibnitz", "Wien", 1688),
    16: ("Leibnitz", "Wien", 1688),
    17: ("Sophie", "Hannover", 1688),
    18: ("Leibnitz", "Wien", 1688),
    19: ("Leibnitz", "Wien", 1689),
    20: ("Sophie", "Hannover", 1689),
    21: ("Leibnitz", "Wien", 1689),
    22: ("Sophie", "Hannover", 1689),
    23: ("Leibnitz", "Ferrara", 1689),
    24: ("Sophie", "Hannover", 1689),
    25: ("Leibnitz", "Modena", 1689),
    26: ("Sophie", "Hannover", 1690),
    27: ("Leibnitz", "Wien", 1690),
    28: ("Sophie", "Linsburg", 1690),
    29: ("Sophie", "Hannover", 1691),
    30: ("Leibnitz", "Hannover", 1691),
    31: ("Sophie", "Rehburg", 1691),
    32: ("Leibnitz", "Braunschweig", 1691),
    33: ("Sophie", "Herrenhausen", 1691),
    34: ("Leibnitz", "Wolfenbüttel", 1691),
    35: ("Sophie", "Ebstorf", 1691),
    36: ("Sophie", "Ebstorf", 1691),
    37: ("Sophie", "Ebstorf", 1691),
    38: ("Leibnitz", "Hannover", 1691),
    39: ("Sophie", "Ebstorf", 1691),
    40: ("Leibnitz", "Hannover", 1691),
    41: ("Sophie", "Ebstorf", 1691),
    42: ("Sophie", "Ebstorf", 1691),
    43: ("Leibnitz", "Hannover", 1691),
    44: ("Sophie", "Göhrde", 1691),
    45: ("Leibnitz", "Hannover", 1692),
    46: ("Sophie", "Celle", 1692),
    47: ("Leibnitz", "Hannover", 1692),
    48: ("Leibnitz", "Hannover", 1692),
    49: ("Sophie", "Hannover", 1692),
    50: ("Sophie", "Göhrde", 1692),
    51: ("Leibnitz", "Wolfenbüttel", 1692),
    52: ("Sophie", "Hannover", 1692),
    53: ("Sophie", "Hannover", 1692),
    54: ("Leibnitz", "Hannover", 1692),
    55: ("Leibnitz", "Hannover", 1693),
    56: ("Sophie", "Hannover", 1693),
    57: ("Leibnitz", "Clausthal", 1694),
    58: ("Leibnitz", "Hannover", 1694),
    59: ("Leibnitz", "Hannover", 1694),
    60: ("Leibnitz", "Hannover", 1694),
    61: ("Leibnitz", "Hannover", 1694),
    62: ("Leibnitz", "Hannover", 1694),
    63: ("Sophie", "Linsburg", 1694),
    64: ("Leibnitz", "Hannover", 1694),
    65: ("Leibnitz", "Hannover", 1694),
    66: ("Leibnitz", "Hannover", 1694),
    67: ("Leibnitz", "Hannover", 1694),
    68: ("Leibnitz", "Hannover", 1694),
    69: ("Leibnitz", "Hannover", 1695),
    70: ("Leibnitz", "Braunschweig", 1695),
    71: ("Sophie", "Linsburg", 1695),
    72: ("Leibnitz", "Hannover", 1695),
    73: ("Leibnitz", "Braunschweig", 1695),
    74: ("Leibnitz", "Hannover", 1696),
    75: ("Leibnitz", "Hannover", 1696),
    76: ("Leibnitz", "Hannover", 1696),
    77: ("Leibnitz", "Hannover", 1696),
    78: ("Sophie", "Linsburg", 1696),
    79: ("Sophie", "Herrenhausen", 1696),
    80: ("Leibnitz", "Hannover", 1696),
    81: ("Leibnitz", "Hannover", 1696),
    82: ("Leibnitz", "Wolfenbüttel", 1697),
    83: ("Sophie", "Herrenhausen", 1697),
    84: ("Sophie", "Hannover", 1697),
    85: ("Leibnitz", "Hannover", 1697),
    86: ("Leibnitz", "Hannover", 1697),
    87: ("Sophie", "Hannover", 1697),
    88: ("Leibnitz", "Hannover", 1697),
    89: ("Leibnitz", "Hannover", 1697),
    90: ("Leibnitz", "Hannover", 1697),
    91: ("Leibnitz", "Hannover", 1697),
    92: ("Leibnitz", "Hannover", 1697),
    93: ("Sophie", "Herrenhausen", 1697),
    94: ("Leibnitz", "Hannover", 1697),
    95: ("Leibnitz", "Hannover", 1697),
    96: ("Sophie", "Herrenhausen", 1697),
    97: ("Leibnitz", "Hannover", 1697),
    98: ("Leibnitz", "Hannover", 1697),
    99: ("Leibnitz", "Braunschweig", 1697),
    100: ("Leibnitz", "Braunschweig", 1697),
    101: ("Leibnitz", "Hannover", 1698),
    102: ("Sophie", "Herrenhausen", 1698),
    103: ("Sophie", "Herrenhausen", 1698),
    104: ("Leibnitz", "Hannover", 1698),
    105: ("Leibnitz", "Hannover", 1699),
    106: ("Leibnitz", "Hannover", 1699),
    107: ("Leibnitz", "Braunschweig", 1699),
    108: ("Leibnitz", "Braunschweig", 1699),
    109: ("Leibnitz", "Hannover", 1699),
    110: ("Leibnitz", "Wolfenbüttel", 1699),
    111: ("Leibnitz", "Wolfenbüttel", 1699),
    112: ("Leibnitz", "Hannover", 1699),
    113: ("Leibnitz", "Hannover", 1699),
    114: ("Leibnitz", "Hannover", 1699),
    115: ("Sophie", "Bruchhausen", 1699),
    116: ("Leibnitz", "Hannover", 1699),
    117: ("Leibnitz", "Hannover", 1699),
    118: ("Sophie", "Linsburg", 1699),
    119: ("Leibnitz", "Hannover", 1699),
    120: ("Sophie", "Linsburg", 1699),
    121: ("Leibnitz", "Hannover", 1699),
    122: ("Leibnitz", "Wolfenbüttel", 1699),
    123: ("Sophie", "Herrenhausen", 1699),
    124: ("Leibnitz", "Berlin", 1700),
    125: ("Sophie", "Herrenhausen", 1700),
    126: ("Leibnitz", "Berlin", 1700),
    127: ("Sophie", "Herrenhausen", 1700),
    128: ("Leibnitz", "Berlin", 1700),
    129: ("Leibnitz", "Berlin", 1700),
    130: ("Sophie", "Herrenhausen", 1700),
    131: ("Leibnitz", "Berlin", 1700),
    132: ("Leibnitz", "Berlin", 1700),
    133: ("Sophie", "Herrenhausen", 1700),
    134: ("Sophie", "Herrenhausen", 1700),
    135: ("Leibnitz", "Berlin", 1700),
    136: ("Sophie", "Herrenhausen", 1700),
    137: ("Leibnitz", "Berlin", 1700),
    138: ("Leibnitz", "Berlin", 1700),
    139: ("Sophie", "Herrenhausen", 1700),
    140: ("Leibnitz", "Berlin", 1700),
    141: ("Sophie", "Herrenhausen", 1700),
    142: ("Leibnitz", "Berlin", 1700),
    143: ("Sophie", "Herrenhausen", 1700),
    144: ("Sophie", "Herrenhausen", 1700),
    145: ("Leibnitz", "Berlin", 1700),
    146: ("Sophie", "Herrenhausen", 1700),
    147: ("Sophie", "Herrenhausen", 1700),
    148: ("Leibnitz", "Lietzenburg", 1700),
    149: ("Sophie", "Herrenhausen", 1700),
    150: ("Leibnitz", "Lietzenburg", 1700),
    151: ("Sophie", "Herrenhausen", 1700),
    152: ("Leibnitz", "Berlin", 1700),
    153: ("Leibnitz", "Hannover", 1701),
    154: ("Sophie", "Herrenhausen", 1701),
    155: ("Leibnitz", "Hannover", 1701),
    156: ("Leibnitz", "Wolfenbüttel", 1701),
    157: ("Sophie", "Herrenhausen", 1701),
    158: ("Sophie", "Herrenhausen", 1701),
    159: ("Leibnitz", "Oranienburg", 1701),
    160: ("Sophie", "Herrenhausen", 1701),
    161: ("Sophie", "Herrenhausen", 1701),
    162: ("Leibnitz", "Berlin", 1701),
    163: ("Leibnitz", "Berlin", 1701),
    164: ("Sophie", "Herrenhausen", 1701),
    165: ("Leibnitz", "Berlin", 1701),
    166: ("Sophie", "Herrenhausen", 1701),
    167: ("Leibnitz", "Berlin", 1701),
    168: ("Sophie", "Hannover", 1701),
    169: ("Leibnitz", "Berlin", 1701),
    170: ("Leibnitz", "Berlin", 1701),
    171: ("Sophie", "Hannover", 1701),
    172: ("Sophie", "Hannover", 1701),
    173: ("Leibnitz", "Berlin", 1701),
    174: ("Leibnitz", "Berlin", 1701),
    175: ("Leibnitz", "Hannover", 1701),
    176: ("Leibnitz", "Berlin", 1701),
    177: ("Sophie", "Hannover", 1702),
    178: ("Leibnitz", "Berlin", 1702),
    179: ("Leibnitz", "Berlin", 1702),
    180: ("Sophie", "Hannover", 1702),
    181: ("Leibnitz", "Berlin", 1702),
    182: ("Sophie", "Hannover", 1702),
    183: ("Leibnitz", "Hannover", 1702),
    184: ("Leibnitz", "Hannover", 1702),
    185: ("Leibnitz", "Berlin", 1702),
    186: ("Sophie", "Herrenhausen", 1702),
    187: ("Sophie", "Herrenhausen", 1702),
    188: ("Sophie", "Herrenhausen", 1702),
    189: ("Leibnitz", "Berlin", 1702),
    190: ("Sophie", "Hannover", 1702),
    191: ("Leibnitz", "Berlin", 1702),
    192: ("Sophie", "Herrenhausen", 1702),
    193: ("Sophie", "Herrenhausen", 1702),
    194: ("Sophie", "Hannover", 1702),
    195: ("Leibnitz", "Lietzenburg", 1702),
    196: ("Sophie", "Herrenhausen", 1702),
    197: ("Sophie", "Herrenhausen", 1702),
    198: ("Sophie", "Herrenhausen", 1702),
    199: ("Leibnitz", "Berlin", 1702),
    200: ("Sophie", "Linsburg", 1702),
    201: ("Sophie", "Linsburg", 1702),
    202: ("Sophie", "Linsburg", 1702),
    203: ("Leibnitz", "Berlin", 1702),
    204: ("Leibnitz", "Berlin", 1702),
    205: ("Sophie", "Linsburg", 1702),
    206: ("Leibnitz", "Berlin", 1702),
    207: ("Sophie", "Linsburg", 1702),
    208: ("Leibnitz", "Berlin", 1702),
    209: ("Leibnitz", "Berlin", 1702),
    210: ("Sophie", "Hannover", 1702),
    211: ("Sophie", "Hannover", 1702),
    212: ("Sophie", "Hannover", 1702),
    213: ("Sophie", "Hannover", 1702),
    214: ("Sophie", "Hannover", 1702),
    215: ("Sophie", "Hannover", 1703),
    216: ("Sophie", "Hannover", 1703),
    217: ("Sophie", "Hannover", 1703),
    218: ("Sophie", "Hannover", 1703),
    219: ("Leibnitz", "Berlin", 1703),
    220: ("Leibnitz", "Berlin", 1703),
    221: ("Leibnitz", "Berlin", 1703),
    222: ("Sophie", "Hannover", 1703),
    223: ("Leibnitz", "Berlin", 1703),
    224: ("Sophie", "Hannover", 1703),
    225: ("Sophie", "Hannover", 1703),
    226: ("Sophie", "Hannover", 1703),
    227: ("Sophie", "Hannover", 1703),
    228: ("Sophie", "Hannover", 1703),
    229: ("Leibnitz", "Berlin", 1703),
    230: ("Sophie", "Hannover", 1703),
    231: ("Leibnitz", "Berlin", 1703),
    232: ("Sophie", "Celle", 1703),
    233: ("Sophie", "Celle", 1703),
    234: ("Leibnitz", "Berlin", 1703),
    235: ("Leibnitz", "Berlin", 1703),
    236: ("Sophie", "Herrenhausen", 1703),
    237: ("Sophie", "Hannover", 1703),
    238: ("Leibnitz", "Braunschweig", 1703),
    239: ("Leibnitz", "Hannover", 1703),
    240: ("Sophie", "Lietzenburg", 1703),
    241: ("Sophie", "Lietzenburg", 1703),
    242: ("Sophie", "Lietzenburg", 1703),
    243: ("Sophie", "Lietzenburg", 1703),
    244: ("Leibnitz", "Herrenhausen", 1703),
    245: ("Leibnitz", "Hannover", 1703),
    246: ("Leibnitz", "Wolfenbüttel", 1704),
    247: ("Leibnitz", "Hannover", 1704),
    248: ("Leibnitz", "Hannover", 1704),
    249: ("Sophie", "Herrenhausen", 1704),
    250: ("Sophie", "Herrenhausen", 1704),
    251: ("Leibnitz", "Hannover", 1704),
    252: ("Leibnitz", "Hannover", 1704),
    253: ("Sophie", "Herrenhausen", 1703),
    254: ("Leibnitz", "Hannover", 1704),
    255: ("Leibnitz", "Lietzenburg", 1704),
    256: ("Sophie", "Herrenhausen", 1704),
    257: ("Sophie", "Herrenhausen", 1704),
    258: ("Leibnitz", "Berlin", 1704),
    259: ("Sophie", "Herrenhausen", 1704),
    260: ("Sophie", "Herrenhausen", 1704),
    261: ("Sophie", "Hannover", 1704),
    262: ("Sophie", "Hannover", 1704),
    263: ("Sophie", "Hannover", 1704),
    264: ("Sophie", "Hannover", 1704),
    265: ("Sophie", "Hannover", 1705),
    266: ("Sophie", "Hannover", 1705),
    267: ("Sophie", "Hannover", 1705),
    268: ("Leibnitz", "Wolfenbüttel", 1705),
    269: ("Leibnitz", "Hannover", 1705),
    270: ("Leibnitz", "Hannover", 1705),
    271: ("Leibnitz", "Hannover", 1705),
    272: ("Leibnitz", "Hannover", 1705),
    273: ("Leibnitz", "Hannover", 1705),
    274: ("Leibnitz", "Hannover", 1705),
    275: ("Leibnitz", "Hannover", 1706),
    276: ("Leibnitz", "Hannover", 1706),
    277: ("Leibnitz", "Hannover", 1706),
    278: ("Leibnitz", "Wolfenbüttel", 1706),
    279: ("Sophie", "Hannover", 1706),
    280: ("Sophie", "Hannover", 1706),
    281: ("Leibnitz", "Wolfenbüttel oder Helmstedt", 1706),
    282: ("Leibnitz", "Helmstedt", 1706),
    283: ("Leibnitz", "Wolfenbüttel", 1706),
    284: ("Leibnitz", "Hannover", 1706),
    285: ("Sophie", "Herrenhausen", 1706),
    286: ("Leibnitz", "Berlin", 1706),
    287: ("Sophie", "Hannover", 1706),
    288: ("Leibnitz", "Berlin", 1706),
    289: ("Sophie", "Hannover", 1706),
    290: ("Leibnitz", "Berlin", 1706),
    291: ("Leibnitz", "Berlin", 1706),
    292: ("Sophie", "Hannover", 1706),
    293: ("Sophie", "Hannover", 1706),
    294: ("Sophie", "Hannover", 1706),
    295: ("Leibnitz", "Berlin", 1706),
    296: ("Sophie", "Hannover", 1706),
    297: ("Sophie", "Hannover", 1706),
    298: ("Leibnitz", "Berlin", 1707),
    299: ("Sophie", "Hannover", 1707),
    300: ("Leibnitz", "Berlin", 1707),
    301: ("Sophie", "Hannover", 1707),
    302: ("Leibnitz", "Berlin", 1707),
    303: ("Sophie", "Hannover", 1707),
    304: ("Leibnitz", "Berlin", 1707),
    305: ("Leibnitz", "Berlin", 1707),
    306: ("Sophie", "Hannover", 1707),
    307: ("Sophie", "Hannover", 1707),
    308: ("Sophie", "Hannover", 1707),
    309: ("Leibnitz", "Berlin", 1707),
    310: ("Leibnitz", "Berlin", 1707),
    311: ("Sophie", "Hannover", 1707),
    312: ("Leibnitz", "Berlin", 1707),
    313: ("Sophie", "Hannover", 1707),
    314: ("Sophie", "Hannover", 1707),
    315: ("Leibnitz", "Berlin", 1707),
    316: ("Sophie", "Hannover", 1707),
    317: ("Sophie", "Hannover", 1707),
    318: ("Leibnitz", "Hannover", 1707),
    319: ("Leibnitz", "Hannover", 1708),
    320: ("Leibnitz", "Regensburg", 1708),
    321: ("Leibnitz", "Berlin", 1709),
    322: ("Sophie", "Hannover", 1709),
    323: ("Leibnitz", "Berlin", 1709),
    324: ("Leibnitz", "Hannover", 1709),
    325: ("Leibnitz", "Hannover", 1710),
    326: ("Leibnitz", "Hannover", 1710),
    327: ("Leibnitz", "Hannover", 1711),
    328: ("Sophie", "Hannover", 1711),
    329: ("Leibnitz", "Hannover", 1711),
    330: ("Sophie", "Hannover", 1711),
    331: ("Leibnitz", "Hannover", 1711),
    332: ("Sophie", "Hannover", 1711),
    333: ("Sophie", "Hannover", 1711),
    334: ("Leibnitz", "Berlin", 1711),
    335: ("Leibnitz", "Berlin", 1711),
    336: ("Leibnitz", "Herrenhausen", 1711),
    337: ("Leibnitz", "Wolfenbüttel", 1711),
    338: ("Sophie", "Herrenhausen", 1711),
    339: ("Leibnitz", "Hannover", 1711),
    340: ("Leibnitz", "Torgau", 1711),
    341: ("Sophie", "Göhrde", 1711),
    342: ("Leibnitz", "Leipzig", 1711),
    343: ("Leibnitz", "Wolfenbüttel", 1712),
    344: ("Sophie", "Hannover", 1712),
    345: ("Leibnitz", "Wolfenbüttel", 1712),
    346: ("Leibnitz", "Karlsbad", 1712),
    347: ("Leibnitz", "Wien", 1712),
    348: ("Sophie", "Hannover", 1713),
    349: ("Leibnitz", "Wien", 1713),
    350: ("Leibnitz", "Wien", 1713),
    351: ("Sophie", "Hannover", 1713),
    352: ("Leibnitz", "Wien", 1713),
    353: ("Leibnitz", "Wien", 1713),
    354: ("Sophie", "Hannover", 1713),
    355: ("Sophie", "Hannover", 1713),
    356: ("Leibnitz", "Wien", 1713),
    357: ("Sophie", "Hannover", 1713),
    358: ("Leibnitz", "Wien", 1713),
    359: ("Sophie", "Hannover", 1713),
    360: ("Sophie", "Hannover", 1713),
    361: ("Leibnitz", "Wien", 1713),
    362: ("Sophie", "Hannover", 1713),
    363: ("Leibnitz", "Wien", 1713),
    364: ("Sophie", "Hannover", 1713),
    365: ("Sophie", "Herrenhausen", 1713),
    366: ("Leibnitz", "Wien", 1713),
    367: ("Sophie", "Hannover", 1713),
    368: ("Sophie", "Hannover", 1713),
    369: ("Leibnitz", "Wien", 1713),
    370: ("Sophie", "Hannover", 1714),
    371: ("Sophie", "Hannover", 1714),
    372: ("Leibnitz", "Wien", 1714),
    373: ("Sophie", "Hannover", 1714),
    374: ("Sophie", "Hannover", 1714),
    375: ("Sophie", "Hannover", 1714),
    376: ("Sophie", "Hannover", 1714),
    377: ("Sophie", "Hannover", 1714),
    378: ("Leibnitz", "Wien", 1714),
    379: ("Leibnitz", "Wien", 1714),
    380: ("Sophie", "Hannover", 1714),
    381: ("Leibnitz", "Wien", 1714),
    382: ("Leibnitz", "Wien", 1714)
}

year_set = {1680, 1684, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703,
            1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714}

# This makes it neccesary to clean up Elb to Elbe and
places_set = {'Champagne', 'Utrecht', 'Lustenburg', 'Bückeburg', 'Brenta', 'Leipzig', 'Hamburg', 'Lehnin', 'Stockholm',
              'Schotte', 'Auvergne', 'Lauenburg', 'Altdorf', 'Mailändisch', 'Po', 'Livland', 'Stade', 'Belgrad',
              'Ungarn', 'Norwegen', 'Australier', 'Regensburg', 'Oberrhein', 'Maas', 'Altona', 'Cambray',
              'Fuentes', 'Halle', 'Bellamont', 'Orléans', 'Wartenberg', 'Gargan', 'Oranienbaum',
              'Pembroke', 'Tiroler', 'Ziesar', 'Kasan', 'Brescello', 'Gundelsheim', 'Holland', 'Sachsen-Merseburg',
              'Het Loo', 'Orange', 'Jena', 'Siena', 'Ruhr', 'Schwarze Meer', 'Salm', 'Köln', 'Spanien', 'Peterwardein',
              'Osnabruck', 'Riga', 'Stamford', 'Gibraltar', 'Warschau', 'Amsterdamer', 'Niederösterreich', 'Afrika',
              'Koblenz', 'Kassel', 'Etsch', 'Krakau', 'Großburgwedel', 'Kniphausen', 'Grieche', 'Friesland', 'Walachei',
              'Buckow', 'Kairo', 'Armenier', 'Pfalz-Neuburg', 'Temeswar', 'Stettin', 'Eider',
              'Maastricht', 'Pamiers', 'Russland', 'Preußen', 'Donauwörth', 'San Spirito', 'Adda', 'Teplitz', 'Böhmen',
              'Kurland', 'Königsmarck', 'Lietzenburg', 'Gotha', 'Nassau', 'Armorika', 'Thorn', 'Mainz', 'Pinneberg',
              'Wangenheim', 'Oranien', 'Gibel', 'Portugal', 'Harburger', 'Veneto', 'Augsburger', 'Schottland',
              'Königsberg', 'Wolfenbüttel', 'OberUngarn', 'Starhemberg', 'Kiel', 'Kopenhagen', 'Grönland', 'Modena',
              'Greiffenstein', 'Bourg', 'Magdeburg', 'Merseburg', 'Ebstorf', 'Ebsdorff', 'Ebdorff', 'Transsilvanien',
              'Antwerpen', 'Ravenna', 'Rehburg', 'Braunschweig',
              'Nienburg', 'Coppenbrügge', 'Hessen', 'Irland', 'Saint-Germain', 'Bretagne', 'Boulogne', 'Baden',
              'Steiermark', 'Lichtenburg', 'Wesel', 'Marienbad', 'Portugiesen', 'Danzig', 'Lüneborg', 'Dover',
              'Wittenberg', 'Deutschland', 'Laxenburg', 'Ahlden', 'Oranienburg', 'Ingenheim', 'Niedersachsen', 'Indien',
              'Hildesheim', 'Salzburg', 'Stormarn', 'Alpen', 'Franzose', 'Münster', 'Chios', 'Freising', 'Kärnten',
              'Nordhausen', 'Porto', 'Charlottenburg', 'Ilok', 'Wildeshausen', 'Nordburg', 'Nimwegen', 'Pommern',
              'Greifswald', 'Condom', 'Bille', 'Weser', 'Ratzeburg', 'Kroatien', 'Frankreich', 'Goslar', 'Kiew',
              'Bevern', 'Frankfurt an der Oder', 'Ormonde', 'Schwaben', 'Oldenburg', 'Kehl', 'Rantzau',
              'Fürstenfeldbruck', 'Euböa', 'Persien', 'Burgdorf', 'Avranches', 'Elbing', 'Smyrna', 'Peine', 'Donau',
              'Idria', 'Augsburg', 'Innsbruck', 'Sizilien', 'Zerbst', 'London', 'Loreto', 'Harz', 'Moskau', 'Memel',
              'Jerusalem', 'Bender', 'Gandersheim', 'Weichsel', 'Moray', 'Spanheim', 'Styrum', 'Campen', 'Ostrog',
              'Meaux', 'Clausthal', 'Konstantinopel', 'Schwedt', 'Walachen', 'Wismar', 'Thüringen', 'Wales',
              'Saint Germain', 'Zell', 'Astrachan', 'Dohna', 'Schlesien', 'Rastatt', 'Borgoforte', 'Aquileja',
              'Kap der Guten Hoffnung', 'Malchow', 'Zweibrücken', 'Vigo', 'Nola', 'Wien', 'Stör', 'Lüttich', 'Litauen',
              'Römer', 'Türkei', 'Melle', 'Flandern', 'Blankenburg', 'Wagenbourg', 'Montepulciano', 'La Trappe',
              'Litauer', 'Seeland', 'Bayern', 'Chaldäa', 'Breslau', 'Monmouth', 'Däne', 'Lübeck', 'Ahlefeldt', 'Essen',
              'Güstrow', 'Oeynhausen', 'Loccum', 'Torgau', 'Bayreuth', 'Paderborn', 'Saint Cyr', 'Hundisburg',
              'Philippsburg', 'Äthiopien', 'Nürnberg', 'Lamspringe', 'Hannover', 'Neuburg', 'Vaudémont', 'Ägypten',
              'Venlo', 'Malta', 'Italiener', 'Tirol', 'Ferrara', 'Helmstedt', 'Alster', 'Straßburg', 'Mailand',
              'Holstein', 'Martinitz', 'Strahlenheim', 'Chinese', 'Ephesus', 'Bonn', 'Shrewsbury', 'Monferrato',
              'Köpenick', 'Kurpfalz', 'Dresden', 'Saint James', 'Steevenswert', 'Finnland', 'Nizza', 'Ursel',
              'Venezianer', 'Soest', 'Marlborough', 'Lothringen', 'Buda', 'Graupen', 'Salisbury', 'Karlsbad', 'Prag',
              'Pfalz', 'Levante', 'Pöllnitz', 'Bamberg', 'Osnabrücker', 'Crossen', 'Württemberg', 'Tokaj', 'Lombardei',
              'Asien', 'Linz', 'Amerika', 'Seesen', 'Sesto', 'Tettau', 'Hanover', 'China', 'Göteborg', 'Trier', 'Maine',
              'Venedig', 'Anhalt', 'Siebenbürgen', 'Posen', 'Breda', 'Holländer', 'Peking', 'Bruchhausen', 'Celle',
              'Meseritz', 'Cadiz', 'Düsseldorf', 'Plittersdorf', 'Pole', 'Pruth', 'München', 'Arenberg', 'Rijswijk',
              'Weyhausen', 'Den Haag', 'Sachsen-Lauenburg', 'Inn', 'Pyrmont', 'Schönhausen', 'Brüssel', 'Rotterdam',
              'Niederlande', 'Mittelmeer', 'Aachen', 'Nauplia', 'Kliszów', 'Bremen', 'Elbe', 'Fürstenberg', 'Mantua',
              'Petersburg', 'Sachsen', 'Rhône', 'Tönning', 'England', 'Herzberg', 'Lenzen', 'Hildesheimer', 'Schweden',
              'Detmold', 'Florenz', 'Salzdahlum', 'Morea', 'Pest', 'Sorbonne', 'Ostsee', 'Neapel', 'Brandenburg',
              'Wassenaer', 'Beichlingen', 'Paris', 'Chaldäer', 'Lyon', 'Sulzbach', 'Linsburg', 'Dixmuiden', 'Spandau',
              'Großbritannien', 'Berlin', 'Osnabrück', 'Hammerstein', 'Vesuv', 'Göhrde', 'Bristol', 'Lissenheim',
              'Sachsen-Gotha', 'Engländer', 'Franken', 'Toskana', 'Savoyen', 'Kanarische Inseln', 'Ägypter', 'Venetien',
              'Rom', 'Schulenburg', 'Polen', 'Genua', 'Zellerfeld', 'Harburg', 'Europa', 'Herford', 'Singen',
              'Hessen-Kassel', 'Nöteburg', 'Spanier', 'Amsterdam', 'Madrid', 'Italien', 'Frankfurt', 'Rhein',
              'Barcelona', 'Genf', 'Maintenon', 'Quedlinburg', 'Pottendorf', 'Türke', 'Nordmeer', 'Burgund',
              'Cambridge', 'Wardein', 'Scarlati', 'Dänemark', 'Hackelberg', 'Dalmatien', 'Homburg', 'Glogau',
              'Maubuisson', 'Wolffenbüttel', 'Newcastle', 'Osterode', 'Namur', 'Schmettau', 'Piemont', 'Sternberg',
              'Borgholzhausen', 'Laxemburg', 'Rotes Meer', 'Potsdam', 'Israel', 'Anjou', 'Mecklenburg', 'Dennem',
              'Tangermünde', 'Heidelberg', 'Ansbach', 'Raab', 'Ulm', 'Europäer', 'Schwede', 'Landsberg', 'Ostfriesland',
              'Brandenburger', 'York', 'Rappach', 'Königstein', 'Lüneburg', 'Ätna', 'Herrenhausen', 'Åbo', 'Turku',
              'Hollandt', 'Cöllen', 'Budapest'}

always_drop = {
    'Gargan', 'Wassenaer', 'Arenberg', 'Bellamont', "Lissenheim", "Schmettau", "Starhemberg", "Lietzenburg",
    'Lissenheim', "Nordburg", "Dennem", "Ormonde", "Pöllnitz", "Strahlenheim", "Wagenbourg", "Veneto", 'Ahlefeldt',
    'Armorika', "San Spirito", "Styrum", 'Harburger', 'Spanheim', 'Scarlati'
}

always_rename = {
    "Hanover": "Hannover", "Ebsdorff": "Ebstorf", 'Ebdorff': "Ebstorf", 'Güstrower': 'Güstrow', 'Åbo': 'Turku',
    'Hollandt': 'Holland', "Cöllen": "Köln", 'Lietzenburger': 'Lietzenburg', 'Osnabrücker': 'Osnabrück',
    'Augsburger': 'Augsburg', 'Hildesheimer': 'Hildesheim', 'Amsterdamer': 'Amsterdam', 'Tiroler': 'Tirol',
    'Osnabrücker': 'Osnabrück', 'Augsburger': 'Augsburg', "Brandenburger": 'Brandenburg', 'Laxemburg': 'Laxenburg',
    'Pest': 'Budapest', 'Buda': 'Budapest', 'Budapestpest': 'Budapest', 'Saint Germain':'Saint-Germain',
}

# zur kathegorisierung der Orte:
nationalities_ethnicities = {
    'Armenier', 'Australier', 'Europäer', 'Franzose', 'Türke',
    'Holländer', 'Italiener', 'Litauer', 'Pole', 'Portugiesen', 'Schwede', 'Spanier', 'Ägypter',
    'Chaldäer', 'Engländer','Römer', 'Schotte', 'Venezianer', 'Walachen',
}

cities = {
    "Aachen", "Ahlden", "Altdorf", "Altona", "Antwerpen", "Astrachan",
    "Avranches", "Barcelona", "Belgrad", "Bender", "Bonn", "Borgoforte", "Boulogne",
    "Brandenburg", "Breda", "Breslau", "Brüssel", "Budapest", "Bückeburg",
    "Cambridge", "Celle", "Clausthal", "Condom", "Danzig", "Den Haag", "Detmold",
    "Dover", "Ebstorf", "Ephesus", "Florenz", "Frankfurt", "Freising", "Fuentes",
    "Fürstenfeldbruck", "Genf", "Genua", "Gibraltar", "Glogau", "Göhrde", "Göttingen",
    "Hackelberg", "Hamburg", "Hannover", "Hildesheim", "Herrenhausen", 'Turku'
    "Innsbruck", "Jena", "Karlsbad", "Kasan", 'Straßburg',
    "Cöllen", "Kassel", "Kiel", "Kliszów", "Köln",
    "Königsberg", "Krakau", "Kopenhagen", "Lamspringe", "Leipzig", "Linz",
    "London", "Lyon", "Madrid", "Maintenon", "Malchow", "Malta", "Mantua",
    "Maastricht", "Marienbad", "Marlborough", "Martinitz", "Maubuisson", "Meaux",
    "Mecklenburg", "Melle", "Memel", "Merseburg", "Meseritz", "Monferrato",
    "Monmouth", "Montepulciano", "Moskau", "München", "Namur", "Nassau", "Nauplia",
    "Neapel", "Newcastle", "Nimwegen", "Nizza", "Nola", "Oeynhausen", "Oldenburg",
    "Oranienburg", "Orléans", "Osnabrück", "Osterode", "Paris", "Peking", "Petersburg",
    "Philippsburg", "Potsdam", "Prag", "Quedlinburg", "Ravenna", "Regensburg",
    "Riga", "Rijswijk", "Rom", "Rotterdam", "Salisbury", "Salzburg", "Schwerin",
    "Seesen", "Siena", "Smyrna", "Sorbonne", "Spandau", "Stade", "Stockholm",
    "Tangermünde", "Teplitz", "Thorn", "Tokaj", "Tönning", "Ulm", "Utrecht", "Venlo",
    "Venedig", "Vigo", "Warschau", "Wesel", "Wien", "Wismar", "Rehburg",
    "York", "Zell", "Zellerfeld", "Zweibrücken", "Schulenburg", "Braunschweig",
    "Elbing", "Cadiz", "Essen", "Borgholzhausen", "Smyrna", "Modena", "Mailand",
    "Innsbruck", "Madrid", "Torgau", "Wien", "Stamford", "Zerbst", "Lenzen",
    "Güstrow", "Nienburg", "Osnabruck", "Wismar", "Nordhausen", "Mainz",
    "Blankenburg", "Bremen", "Goslar", "Berlin", "Marienbad", "Ulm", "Ansbach",
    "Neuburg", "Singen", "Jerusalem", "Münster", "Bristol", "Teplitz", "Mantua",
    "Amsterdam", "Heidelberg", "Greifswald", "Charlottenburg", "Köln", "Dresden",
    "Hannover", "Kiel", "Lübeck", "Peine", "Soest", "Brüssel", "Göteborg",
    "Nürnberg", "Bamberg", "Augsburg", "Magdeburg", "Wittenberg", "Halle",
    "Salzburg", "Hildesheim", "Trier", "Düsseldorf",
    'Ferrara', 'Frankfurt an der Oder', 'Gandersheim', 'Gotha', 'Güstrower',
    'Harburg', 'Herford', 'Helmstedt', 'Idria', 'Kehl', 'Kiew', 'Koblenz',
    'Konstantinopel', 'Landsberg', 'Lehnin', 'Lüttich', 'Lüneburg', 'Paderborn',
    'Pembroke', 'Peterwardein', 'Posen', 'Ratzeburg', 'Rastatt', 'Saint-Germain',
    'Saint James', 'Stettin', 'Shrewsbury', 'Sesto', 'Temeswar', 'Wangenheim',
    'Wesel', 'Wildeshausen', 'Wolfenbüttel', 'Bayreuth', 'Beichlingen',
    'Bruchhausen', 'Buda', 'Burgdorf', 'Donauwörth', 'Kärnten', 'Köpenick', 'Laxenburg',
    'Plittersdorf', 'Porto', 'Pottendorf', 'Rantzau', 'Saint Germain', 'Siebenbürgen', "Aquileja", "Bourg", "Brescello",
    "Buckow", "Cambray", "Campen", "Chios", "Coppenbrügge", "Crossen", "Dixmuiden", "Dohna", "Fürstenberg",
    "Großburgwedel", "Gundelsheim", "Hammerstein", "Herzberg", "Homburg", "Kairo", "Kniphausen", "Königstein",
    "Lauenburg", "Linsburg", "Loreto", "Orange", "Pamiers", "Pinneberg", "Pyrmont", "Raab", "Salzdahlum",
    'Bevern', 'Graupen', 'Hundisburg', "Ingenheim", "Königsmarck", "Loccum", "Schwedt", "Schönhausen", "Lüneborg",
    'Ostrog', "Rappach", "Saint Cyr", "Sulzbach", "Tettau", "Weyhausen", "Ziesar", "Ursel", "Oranienbaum",
    "Sternberg", "Wartenberg", "Steevenswert"
}
countries = {
    "Indien", "Dänemark", "Polen", "Frankreich", "Deutschland", "Türkei",
    "Preußen", "Russland", "Spanien", "Schweden", "Ungarn", "Norwegen",
    "Ägypten", "Niederlande", "Italien", "England", "Irland",
    "Grönland", "Finnland", "Äthiopien", "Portugal", "Israel", "China", "Großbritannien",
    "Kroatien", "Litauen", "Schottland"
}

continents = {"Amerika", "Afrika", "Asien", "Europa", "Franken"}

regions = {
    "Maine", "Anhalt", "Baden", "Bayern", "Burgund", "Böhmen", "Dalmatien", "Friesland", "Holland", "Holstein",
    "Hessen", "Hessen-Kassel", "Kurland", "Kurpfalz", "Lothringen", "Niedersachsen",
    "Niederösterreich", "Ostfriesland", 'Persien', 'Pfalz', 'Pfalz-Neuburg', 'Pommern', 'Sachsen-Gotha', 'Sachsen',
    'Sachsen-Lauenburg', 'Sachsen-Merseburg', 'Schlesien', 'Sizilien', 'Steiermark', 'Walachei', 'Wales', 'Württemberg',
    'Levante', 'Anjou', 'Auvergne', 'Bretagne', 'Champagne', 'Euböa', 'Livland', 'Lombardei', "Moray", "Morea",
    'Piemont', "Stormarn",
    'Salm', 'Savoyen', 'Seeland', "Thüringen", "Tirol", "Toskana", "Transsilvanien", "Vaudémont", "Venetien"
}

landmarks = {"Vesuv", "Alpen", "Harz", "Kap der Guten Hoffnung", "Ätna", "Gibel"}

rivers = {
    "Rhône", "Weichsel", "Alster", "Donau", "Elbe", "Etsch", "Eider", "Inn", "Maas", "Rhein", "Oberrhein", "Po",
    "Ruhr", "Weser", "Bille", "Brenta", "Pruth", "Stör", "Adda",
}

water_bodies = {'Mittelmeer', 'Nordmeer', 'Ostsee', 'Schwarze Meer', }

misc = {
    "Ilok", "Het Loo", "La Trappe", "Lichtenburg", "Lustenburg", "Nöteburg", "Oranien", "Wardein",
    "Styrum", 'Chaldäa', "Greiffenstein",
}
